### ISSUE TITLE
Allow "-R <relaton-rxl>" option to be enabled via "-x rxl

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-cli#19]
Relaton RXL files should allow generated through specifying the `-x rxl` option. This allows us to simplify the Makefiles by enabling an extra file extension in the document attributes.

Alternatively, we can expose the document attribute `:mn-relaton-output-file: <blah>` to set the option for `-R`.

**Comment by opoudjis** [comment]
Implemented -x rxl in metanorma gem

**Comment by opoudjis** [comment]
Implemented :mn-relaton-output-file: in metanorma gem.

**Comment by opoudjis** [comment]
Ensured that relaton option generates file relative to the directory the source file is in.
