### ISSUE TITLE
Build failure in Ruby HEAD since Travis now does not necessarily include `bundler` gem

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-cli#24]
See https://travis-ci.org/riboseinc/metanorma-cli/jobs/475140199

Apparently Travis' RUBY HEAD image doesn't have `bundler` by default anymore.

**Comment by opoudjis** [comment]
No, they've just upgraded to the next major version of bundler. Affects all gems that invoke bundler for development.

**Comment by opoudjis** [comment]
I have updated all gemspecs, and need to regenerate all Gemfile.lock files. I am only pushing metanorma-cli for now, but this will catch up when I do next global release.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
