### ISSUE TITLE
Enhance manifest to deal with relaton YAML

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-cli#6]
The YAML input in https://github.com/riboseinc/relaton-server-csd/blob/master/data/repo/index.yaml should be able to drive the manifest generator as well, but with Relaton XML links.

Specifically, the Manifest HTML (i.e. the "HTML index" at /index.html), should contain for each entry:

* a relaton XML link
* a metanorma XML output
* a metanorma HTML output
* a metanorma PDF output
* a title description and doc identifier

**Comment by opoudjis** [comment]
I have generated the following:

in Metanorma-cli:

`exe/metanorma-manifest -t csd -R /Users/nickn/Documents/Arbeit/upwork/ribose/relaton-server-csd/data/out spec/assets/index.yaml`

The -R option is the root directory where the relaton-server-csd output (the XML bibdata files) are located.

[index.html.zip](https://github.com/riboseinc/metanorma-cli/files/2414949/index.html.zip)

**Comment by ronaldtse** [comment]
@opoudjis could you update this design to the one in https://github.com/riboseinc/csd-style/tree/master/manifest ? I've updated the design and CSS, looks better now. Thanks!

**Comment by opoudjis** [comment]
And https://www.calendarstandards.org as target

**Comment by opoudjis** [comment]
Confused: the CSS you have pointed to is much plainer than Pierre's, which is much plainer than the calendarstandards target. I am switching to that as target.

**Comment by opoudjis** [comment]
I have this working, through the pieces are precariously put together.

metanorma-cli now has the scripts relaton-doc and relaton-manifest

We presuppose that you have already run relaton-server-csd bin/calconnect_index, to generate Relaton XML from the same YAML file.

`exe/relaton-manifest -R /Users/nickn/Documents/Arbeit/upwork/ribose/relaton-server-csd/data/out spec/assets/index.yaml`

The -R parameter is where  the bin/calconnect_index outputs are. This is actually meant to be a relative link to be inserted into the HTML.

spec/assets/index.yaml in metanorma-cli is the sample file. The YAML file is meant to contain the stylesheet to be used:

`htmlstylesheet: spec/assets/style.css`

I am attaching the before and after files, which the script above is meant to find under spec/assets. 

[manifest.zip](https://github.com/riboseinc/metanorma-cli/files/2420054/manifest.zip)

**Comment by ronaldtse** [comment]
Thanks , then the one thing I need is a script that extracts Relaton XML from a Metanorma source document. 

Then we can chain all Metanorma documents -> Relaton collection -> HTML index.

**Comment by ronaldtse** [comment]
So this is now the ticket to support extracting Relaton XML from a Metanorma document.

**Comment by ronaldtse** [comment]
I’ll move the Relaton stuff to relaton-cli.

**Comment by ronaldtse** [comment]
"Replace directory name + implicit file name with explicit filename". I'd much prefer to take out the directory from the workflow.

Thanks.

**Comment by opoudjis** [comment]
OK, proceeding. I suspect you will also want a workflow to extract Relaton XML from a directory of Metanorma XML files, but I will only do that when you ask me to. (You may have done so in chat.)

**Comment by ronaldtse** [comment]
Yes that would be an awesome addition. However, we probably want to do so for an input "directory" (or a directory tree), will it be grouped in Parts? Or any grouping? Or should we just use a YAML file to dictate the explicit paths of the files? Perhaps there's no need for "metanorma file discovery"?

**Comment by opoudjis** [comment]
It is possible to do away completely with the YAML file, and use folder structure to indicate any groupings: in theory, you can extract all information out of the Relaton XML. I'd rather not, and make any such structure explicit: we need metadata for the name and author of the collection, and real titles for the parts, so there is going to be a YAML structure anyway.

The sensible way forward is to iterate through all documents nominated in the YAML, and export their relaton XML into a separate directory. Making that separate ticket.

**Comment by ronaldtse** [comment]
I fully agree with making all files explicit. We can always use another supplementary script that generate the index YAML from a directory structure. Such script will be separate from core Relaton.
